# Generated by Django 4.2.4 on 2023-08-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_category_create_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('last_modified_date', 'name'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Products'},
        ),
    ]
