# Generated by Django 4.2.4 on 2023-09-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(max_length=50, verbose_name='номер телефона'),
        ),
    ]
